<?php
    return [
        [
            'anno' => '2021-giugno/dicembre',
            'nome' => 'Digital divide and COVID-19: which effects on students’ achievement?',
            'descrizione' => 'Indagine sull\'effetto del “digital divide” rispetto alle performance degli studenti, come conseguenza della pandemia di COVID-19.',
            'area' => 'Scuola',
        ],
        [
            'anno' => '2021-2022',
            'nome' => 'Action for 5G-edu',
            'descrizione' => 'Come utilizzare la Realtà Aumentata a scuola e nella formazione professionale rappresentando “concetti” virtuali piuttosto che “oggetti” virtuali. In collaborazione con VODAFONE e la start-up FifthIngenium.',
            'area' => 'Scuola',
        ],
        [
            'anno' => '2020-2022',
            'nome' => 'TWIN',
            'descrizione' => 'Sulla rigenerazione territoriale, il turismo lento, il recupero di edifici o aree dismesse e l’inclusione sociale. Progetto finanziato dal Politecnico di Milano, nell\'ambito del programma “Polisocial”. www.twin.polimi.it',
            'area' => 'Società',
        ],
        [
            'anno' => '2020-2021',
            'nome' => 'EIT-Urban Mobility',
            'descrizione' => 'Nell\'ambito dei programmi Horizon 2020 e Horizon Europe, preparazione di un MOOC (Massive Online Open Course) su “Grant Writing” (2020) e organizzazione di una Summer School in collaborazione con l\'Università di Rennes (luglio 2021) per l\'EIT Master School Urban Mobility (programma di doppia laurea cofinanziato dall\'Istituto Europeo di Innovazione e Tecnologia).',
            'area' => 'Scuola',
        ],
        [
            'anno' => '2020-2022',
            'nome' => 'BASE5G',
            'descrizione' => 'Utilizzo di Realtà Virtuale e Aumentata per migliorare i processi di insegnamento/apprendimento. In collaborazione con Vodafone, AKKA, LIFE, ANOTHEREALITY, YAPE.',
            'area' => 'Scuola',
        ],
        [
            'anno' => '2018-2021',
            'nome' => 'ELSE',
            'descrizione' => 'Ambienti di apprendimento e simulazione eco/logici nell\'istruzione superiore (programma Erasmus+). Un progetto per estendere il modello della classe rovesciata all\'istruzione superiore tramite ambienti di simulazione e un sistema di raccolta della “risposta” degli studenti. www.elseproject.eu',
            'area' => 'Scuola',
        ],
        [
            'anno' => '2018-2020',
            'nome' => 'VODAFONE 5G',
            'descrizione' => 'Sull\'uso della realtà virtuale e aumentata per valorizzare il turismo culturale (caso d\'uso “Turismo 4.0”).',
            'area' => 'Beni culturali',
        ],
        [
            'anno' => '2018-2021',
            'nome' => 'SCAR',
            'descrizione' => 'Sul ruolo delle scuole per migliorare la comprensione e la comunicazione delle aree urbane periferiche. Progetto finanziato dal Politecnico di Milano, nell\'ambito del programma “Polisocial". www.scar.polimi.it',
            'area' => 'Scuola',
        ],
        [
            'anno' => '2017-in corso',
            'nome' => 'EIT-Digital',
            'descrizione' => 'Nell\'ambito dei programmi Horizon 2020 e Horizon Europe, diverse azioni per valorizzare i corsi Innovation & Entrepreneurship della EIT Digital Master School (programma di doppia laurea co-finanziato dall\'Istituto Europeo di Innovazione e Tecnologia), con approcci educativi innovativi volti a promuovere il talento digitale imprenditoriale “a forma di T” tra gli studenti di Ingegneria Informatica.',
            'area' => 'Scuola',
        ],
        [
            'anno' => '2017',
            'nome' => 'EIT-Digital/MOOC',
            'descrizione' => 'Sviluppo di un MOOC (Massive Online Open Course) per Coursera, sul corso “Recommender System” del prof. P. Cremonesi, del Politecnico di Milano.',
            'area' => 'Scuola',
        ],
        [
            'anno' => '2017-2018',
            'nome' => 'Museum’s tales',
            'descrizione' => 'Esperienza formativa con un Liceo Scientifico italiano (Liceo Scientifico op. Scienze Applicate “A. Berenini”) di Fidenza , in collaborazione con il museo locale (Museo della Diocesi di Fidenza). Sono stati realizzati un sito web e 3 narrazioni multimediali. www.museocattedraledifidenza.it',
            'area' => 'Beni culturali/Scuola',
        ],
        [
            'anno' => '2016-2018',
            'nome' => 'DIS-CODE',
            'descrizione' => 'Scollegato, scoraggiato, disabilitato? Programmiamo! (“Disconnected, discouraged, disenabled? Let’s code!”). Programma Erasmus+ con Fondazione Politecnico di Milano, sull\'introduzione del pensiero computazionale a scuola.',
            'area' => 'Scuola',
        ],
        [
            'anno' => '2015-2018',
            'nome' => 'City4Age',
            'descrizione' => 'Un progetto Horizon 2020, coordinato da HOC-LAB, sulla prevenzione, basata sulla comunicazione, della fragilità nella popolazione anziana in Europa: sono stati coinvolti 16 partner e 6 città pilota.',
            'area' => 'Società',
        ],
        [
            'anno' => '2015-2017',
            'nome' => 'EBA',
            'descrizione' => 'European Badge Alliance. Programma Erasmus+, sull\'uso dei badge nell\'istruzione e formazione.',
            'area' => 'Scuola',
        ],
        [
            'anno' => '2013-2015',
            'nome' => 'TALES',
            'descrizione' => 'Programma Comenius, sullo storytelling digitale a scuola.',
            'area' => 'Scuola',
        ],
        [
            'anno' => '2013-2018',
            'nome' => 'LEONARDO - HALL OF PLANKS',
            'descrizione' => '2013-2015 e 2018. Collaborazione di ricerca applicata per comunicare le attività di restauro della Sala delle Asse di Leonardo da Vinci al Castello Sforzesco di Milano.',
            'area' => 'Beni culturali',
        ],
        [
            'anno' => '2013-2015',
            'nome' => 'EDOC@WORK3.0',
            'descrizione' => ' Insegnamento/apprendimento/lavoro su cloud. Progetto PON Ricerca e Competitività. Diverse azioni per innovare la didattica: digital storytelling, learning objects e un portale di risorse educative.',
            'area' => 'Scuola',
        ],
        [
            'anno' => '2013',
            'nome' => 'PoliCultura & EXPO 2015',
            'descrizione' => '2013-2015. Edizione speciale del concorso PoliCultura come "Progetto Scuola" per l\'Esposizione Universale di Milano.',
            'area' => 'Scuola',
        ],
        [
            'anno' => '2012',
            'nome' => 'Voices, Words and Texts from the Campania Region',
            'descrizione' => '2012-2015. Valorizzazione attraverso storie digitali multimediali, applicazioni interattive e un SW di archiviazione per tre archivi della regione Campania (progetto PON).',
            'area' => 'Beni culturali',
        ],
        [
            'anno' => '2010-2013',
            'nome' => 'COMFIT',
            'descrizione' => 'Progetto Interreg, sulla Comunicazione Multimediale Integrata per il Turismo.',
            'area' => 'Beni culturali',
        ],
        [
            'anno' => '2010',
            'nome' => 'A day in Roman Milan',
            'descrizione' => 'Una narrazione multimediale e multicanale che racconta la vita di 5 “personaggi” nell\'antica Milano romana.',
            'area' => 'Beni culturali',
        ],
        [
            'anno' => '2010',
            'nome' => 'Nippon',
            'descrizione' => 'n collaborazione con Tec-Lab dell\'Università della Svizzera italiana e il “Polo Culturale” di Lugano, GUIDA MULTIMEDIALE a 4 mostre sulla cultura giapponese.',
            'area' => 'Beni culturali',
        ],
        [
            'anno' => '2009-2012',
            'nome' => 'L4All',
            'descrizione' => 'Insegnamento per tutti: stanno imparando tutti? (“Learning for all: is everyone learning?”). Il progetto Firb indaga su come la tecnologia per l\'istruzione può migliorare l\'inclusione.',
            'area' => 'Scuola',
        ],
        [
            'anno' => '2009',
            'nome' => 'Look at me. Faces and gazes in art',
            'descrizione' => 'In collaborazione con Tec-Lab dell\'Università della Svizzera Italiana, il Museo Cantonale d\'Arte e il Museo d\'Arte di Lugano (CH). Guida multimediale a una mostra sui volti e gli sguardi nell\'arte.',
            'area' => 'Beni culturali',
        ],
        [
            'anno' => '2008-2009',
            'nome' => 'Communicating the quality of organic products, from the web to iPhone',
            'descrizione' => 'Accordo tra il “Consiglio per la Ricerca e la sperimentazione in Agricoltura – Centro di ricerca per la Produzione delle Carni ed il Miglioramento genetico (CRA-PCM)”e il Dipartimento di Elettronica e Informazione del Politenico di Milano, per ricercare nuove modalità multimediali per veicolare la qualità dei prodotti biologici.',
            'area' => 'Società',
        ],
        [
            'anno' => '2008-2012',
            'nome' => 'Queens of Italy',
            'descrizione' => 'Quattro narrazioni multimediali su personaggi storici femminili rilevanti. In collaborazione con Inner Wheel Club di Monza (Italia). www.regineditalia.it',
            'area' => 'Beni culturali',
        ],
        [
            'anno' => '2008',
            'nome' => 'Enigma Helvetia Tales',
            'descrizione' => '2008. In collaborazione con Tec-Lab dell\'Università della Svizzera Italiana, il Museo Cantonale d\'Arte e il Museo d\'Arte di Lugano (CH), una guida multimediale ad una mostra sulla cultura svizzera.',
            'area' => 'Beni culturali',
        ],
        [
            'anno' => '2007-2008',
            'nome' => 'Polilab-Kids',
            'descrizione' => 'Una libreria di animazioni educative che rispondono alle domande dei bambini sulle materie STEM.',
            'area' => 'Scuola',
        ],
        [
            'anno' => '2007 - in corso',
            'nome' => 'PoliCollege',
            'descrizione' => '2007 (1a ed), 2012 (2a ed), 2019-in corso (3a ed). Corsi online per studenti delle scuole superiori molto motivati, su materie STEM di livello universitario.',
            'area' => 'Scuola',
        ],
        [
            'anno' => '2007-2009',
            'nome' => 'Learning@Socialsport',
            'descrizione' => 'Esperienze educative in Ambienti Virtuali Multi-utente su tematiche etiche, sociali e psicologiche legate allo sport. In collaborazione con Master SBS Verde Sport (dal marchio di moda italiano Benetton), la Fondazione Italiana Accenture e del Comitato Olimpico Nazionale Italiano (CONI). Sono stati coinvolti più di 350 giovani atleti di associazioni sportive italiane.',
            'area' => 'Scuola',
        ],
        [
            'anno' => '2007-2010',
            'nome' => 'Roman Milan',
            'descrizione' => 'In collaborazione con il Museo Civico Archeologico di Milano, con il patrocinio della Regione Lombardia: tre "racconti" multimediali sul museo (Sezione Romana e Sezione Arte Gandhara).',
            'area' => 'Beni culturali',
        ],
        [
            'anno' => '2007',
            'nome' => 'Hermann Hesse: Seekers of Truth',
            'descrizione' => 'In collaborazione con Tec-Lab dell\'Università della Svizzera Italiana, il Museo Hermann Hesse di Montagnola, Lugano (CH). Storie multimediali sulla comunità di “Monte Verità”, con sede vicino a Lugano, dove Hermann Hesse ha trascorso qualche tempo.',
            'area' => 'Beni culturali',
        ],
        [
            'anno' => '2006',
            'nome' => 'MAPS',
            'descrizione' => 'Attività di marketing per la promozione del patrimonio culturale siriano, in collaborazione con il ministero per il turismo e la cultura siriano.',
            'area' => 'Beni culturali',
        ],
        [
            'anno' => '2006 - in corso',
            'nome' => 'PoliCultura',
            'descrizione' => 'Un concorso nazionale sullo storytelling digitale collaborativo a scuola, basato su “1001storia”, uno strumento di authoring progettato e implementato da HOC-LAB. Più di 42.000 studenti, dalla scuola materna alle superiori, hanno partecipato finora.',
            'area' => 'Scuola',
        ],
        [
            'anno' => '2005-2011',
            'nome' => 'Hi-Tech',
            'descrizione' => 'Summer school di una settimana (preparate da un corso online di un mese) su materie STEM, per studenti delle scuole superiori, presso il Politecnico di Milano .',
            'area' => 'Scuola',
        ],
        [
            'anno' => '2005-2006',
            'nome' => 'Stori@Lombardia',
            'descrizione' => 'Esperienze didattiche in Ambienti Virtuali Multi-utente sulla storia medievale della regione Lombardia. Con il patrocinio della Regione Lombardia. Sono stati coinvolti più di 1.100 studenti del Nord Italia, dalle medie alle superiori.',
            'area' => 'Scuola',
        ],
        [
            'anno' => '2004-2008',
            'nome' => 'Learning@Europe',
            'descrizione' => 'Esperienze educative in Ambienti Virtuali Multi-utente, sulla storia europea. Con il supporto di Accenture Foundation, nell\'ambito del programma di investimento Accenture Corporate Citizenship, realizzato in collaborazione con la Fondazione Italiana Accenture. Sono stati coinvolti più di 6.000 studenti delle scuole superiori di 18 paesi europei e degli Stati Uniti (cadetti di West Point).',
            'area' => 'Scuola',
        ],
        [
            'anno' => '2003-2005',
            'nome' => 'WED',
            'descrizione' => 'WEB come Dialogo, sull’interpretazione dell\'interazione con un sito web in termini di dialogo. Fondo nazionale svizzero per la ricerca.',
            'area' => 'Società',
        ],
        [
            'anno' => '2002-2005',
            'nome' => 'DICE',
            'descrizione' => 'Infrastrutture distribuite per i beni culturali. Costruzione di un ambiente "peer to peer" per la gestione e la diffusione del patrimonio culturale.',
            'area' => 'Scuola',
        ],
        [
            'anno' => '2002-2004',
            'nome' => 'SEE',
            'descrizione' => '2002-2004. Shrine Educational Experience: in collaborazione con il museo di Israele e con il sostegno della Fondazione Dorot, sui “Rotoli del Mar Morto” e le questioni religiose, storiche, sociologiche ad essi connesse. Coinvolti oltre 1.400 studenti delle scuole medie e superiori provenienti da Italia, Israele e Belgio.',
            'area' => 'Beni culturali/Scuola',
        ],
        [
            'anno' => '2000-2002',
            'nome' => 'VNET5',
            'descrizione' => 'Creazione avanzata di prodotti incentrati sull\'utente. Programma IST dell\'Unione Europea.',
            'area' => 'Società',
        ],
        [
            'anno' => '2000',
            'nome' => 'HELP',
            'descrizione' => 'Vedere un\'opera d\'arte di persone ipovedenti. Commissione Europea, Cultura 2000.',
            'area' => 'Società',
        ],
    ];
